[package]
name = "slackify-markdown"
version = "0.1.0"
authors = ["Jonathon Belotti <jonathon.bel.melbourne@gmail.com>"]
edition = "2018"

[dependencies]
pulldown-cmark = "0.5.2"
structopt = "0.2.10"
